services:
  platform-core-api:
    image: elatusdevops/akademiaplus-platform-core-api:qa
    build:
      context: .
      dockerfile: Dockerfile
    container_name: platform-core-api-qa
    ports:
      - "8443:8443"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
