openapi: 3.0.3
info:
  title: Platform Core API - Lead Management Module
  description: Aggregator spec for the lead-management module
  version: 1.0.0

paths:
  /lead-management/demo-requests:
    $ref: 'demo-request.yaml#/paths/~1lead-management~1demo-requests'
  /lead-management/demo-requests/{id}:
    $ref: 'demo-request.yaml#/paths/~1lead-management~1demo-requests~1{id}'

components:
  schemas:
    DemoRequestCreationRequest:
      $ref: 'demo-request.yaml#/components/schemas/DemoRequestCreationRequest'
    DemoRequestCreationResponse:
      $ref: 'demo-request.yaml#/components/schemas/DemoRequestCreationResponse'
    GetDemoRequestResponse:
      $ref: 'demo-request.yaml#/components/schemas/GetDemoRequestResponse'
    GetAllDemoRequests200Response:
      $ref: 'demo-request.yaml#/components/schemas/GetAllDemoRequests200Response'
    ErrorResponse:
      $ref: 'demo-request.yaml#/components/schemas/ErrorResponse'
