api.baseurl=http://localhost:8080
api.user-management.employee.base-url=/v1/user-management/employees
api.user-management.collaborator.base-url=/v1/user-management/collaborators
api.user-management.adult-student.base-url=/v1/user-management/adult-students
api.user-management.tutor.base-url=/v1/user-management/tutors
api.user-management.minor-student.base-url=/v1/user-management/minor-students
