api.coordination.course.base-url=/v1/course-management/courses
api.coordination.schedule.base-url=/v1/course-management/schedules
api.coordination.course-event.base-url=/v1/course-management/course-events