/*
 * Copyright (c) 2026 ElatusDev
 * All rights reserved.
 *
 * This code is proprietary and confidential.
 * Unauthorized copying, distribution, or modification is strictly prohibited.
 */
package com.akademiaplus.task;

import com.akademiaplus.infra.persistence.model.TenantScoped;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.SQLDelete;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity representing a task in the multi-tenant platform.
 * Tasks are assigned to users (students, employees, tutors, or collaborators)
 * and can be tracked through their lifecycle: PENDING, IN_PROGRESS, COMPLETED, or OVERDUE.
 *
 * @author ElatusDev
 * @since 1.0
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Scope("prototype")
@Component
@Entity
@Table(name = "tasks")
@SQLDelete(sql = "UPDATE tasks SET deleted_at = CURRENT_TIMESTAMP WHERE task_id = ? AND tenant_id = ?")
@IdClass(TaskId.class)
public class TaskDataModel extends TenantScoped {

    /** Default status assigned to newly created tasks. */
    public static final String DEFAULT_STATUS = "PENDING";

    /** Default priority assigned to newly created tasks. */
    public static final String DEFAULT_PRIORITY = "MEDIUM";

    /**
     * Unique identifier for the task within the tenant.
     * Auto-generated by {@code EntityIdAssigner}.
     */
    @Id
    @Column(name = "task_id")
    private Long taskId;

    /**
     * Title of the task. Brief description of what needs to be done.
     */
    @Column(name = "title", nullable = false, length = 200)
    private String title;

    /**
     * Detailed description of the task.
     */
    @Column(name = "description", length = 2000)
    private String description;

    /**
     * The ID of the user assigned to this task.
     */
    @Column(name = "assignee_id", nullable = false)
    private Long assigneeId;

    /**
     * The type of assignee: STUDENT, EMPLOYEE, TUTOR, or COLLABORATOR.
     */
    @Column(name = "assignee_type", nullable = false, length = 20)
    private String assigneeType;

    /**
     * The date by which this task should be completed.
     */
    @Column(name = "due_date", nullable = false)
    private LocalDate dueDate;

    /**
     * Priority level: LOW, MEDIUM, HIGH, or URGENT.
     */
    @Column(name = "priority", nullable = false, length = 10)
    private String priority;

    /**
     * Current status: PENDING, IN_PROGRESS, COMPLETED, or OVERDUE.
     */
    @Column(name = "status", nullable = false, length = 15)
    private String status;

    /**
     * The ID of the user who created this task.
     */
    @Column(name = "created_by_user_id", nullable = false)
    private Long createdByUserId;

    /**
     * Timestamp when the task was marked as completed. Null if not yet completed.
     */
    @Column(name = "completed_at")
    private LocalDateTime completedAt;
}
